### ISSUE TITLE
Map element selectors by.css() using id (#foo) and classes (.bar)

### ISSUE THREAD

**Issue by ramonvictor** [ramonvictor/gulp-protractor-qa#5]
Support multiple classes (.foo.bar) ?

**Comment by stramel** [comment]
@ramonvictor Will this be solved with the refactor?

**Comment by stramel** [comment]
@ramonvictor bump

**Comment by ramonvictor** [comment]
@stramel sorry for late reply, but this issue is not fixed yet. It's a bigger problem, because we'll probably need to use another html (angular views) compilation process replacing current `cheerio` implementation.

**Comment by stramel** [comment]
This seems like it has a couple parts,

* multiple selectors
* `nth-child` selectors

The `nth-child` selectors can't be done without compilation.

However, I think you could probably handle the multiple selectors using some kind of recursive search building off of what you have already done in the refactor.

**Comment by stramel** [comment]
I would say we close this out for a issue specifically related to `:nth-child` support since multiple selectors now works.

**Comment by ramonvictor** [comment]
@stramel I agree with you. I'll update a few more things in the readme until tomorrow an then `npm publish`, then closing all fixed issues here.

**Comment by ramonvictor** [comment]
[v0.2.0](https://www.npmjs.com/package/gulp-protractor-qa) is out, so closing issue. Let's open another issue for `:nth-child`.
